
from django.core.exceptions import ValidationError

class MyValidationError(ValidationError):
    pass
