
from django.core.exceptions import ValidationError

class CategoryValidationError(ValidationError):
    pass
